#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

if [ "$1" = 'apache2-foreground' -a "$(id -u)" = '0' ]; then
	chown -R www-data:www-data /var/www/html/themes
  chown -R www-data:www-data /var/www/html/modules
  chown -R www-data:www-data /var/www/html/profiles
  chown -R www-data:www-data /var/www/html/sites
fi

exec "$@"
